# empty_item_single_line = false
brace_style = "PreferSameLine"
edition = "2018"
fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
inline_attribute_width = 100
match_arm_blocks = false
max_width = 100
merge_derives = false
merge_imports = true
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
version = "Two"
where_single_line = true
