empty_item_single_line = true
#fn_single_line = true
#format_strings = true
brace_style = "PreferSameLine"
edition = "2018"
fn_args_layout = "Compressed"
# format_code_in_doc_comments = true # sometimes also rewrites // -> /* .. */ in structs
format_macro_bodies = true
format_macro_matchers = true
inline_attribute_width = 100
match_arm_blocks = false
max_width = 100
merge_derives = false
merge_imports = true
# normalize_comments = true # rewrites and reindents /* .. */ blocks to //
overflow_delimited_expr = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
version = "Two"
where_single_line = true
